twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/Media/templates': Media
        '%kernel.project_dir%/src/Settings/templates': Settings
        '%kernel.project_dir%/src/Dashboard/templates': Dashboard
        '%kernel.project_dir%/src/Videographer/templates': Videographer
        '%kernel.project_dir%/src/Project/templates': Project
        '%kernel.project_dir%/src/Client/templates': Client

when@test:
    twig:
        strict_variables: true
